---

- hosts: kubernetes-master-nodes
  vars:
    podNetwork: "10.244.0.0/16"

  tasks:

    
    - name: initialise kubernetes cluster
      shell: kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr={{ podNetwork }} --apiserver-cert-extra-sans={{ inventory_hostname }},{{ ansible_host }}
      register: kubeadmInitLog

    - name: copy kubeadm log  
      set_fact:
        kubeadmInitLogFact: "{{ kubeadmInitLog }}"

    - name: get join token
      shell: echo "{{ kubeadmInitLogFact.stdout }}" > /root/kubeadm-init-output.txt && cat /root/kubeadm-init-output.txt | grep -i "kubeadm join" > /root/kubeadm-token.txt

    - name: create kube home directory
      shell: mkdir -p $HOME/.kube  

    - name: copy kube config
      shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      become: true

    - name: fix kube config ownership
      shell: chown $(id -u):$(id -g) $HOME/.kube/config
      become: true  

    - name: install kubernetes dns
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml